### PR TITLE
remove unnecessary scripts.

### PR DESCRIPTION
**Pull request by chitacan**

### CODE REVIEW

**Comment by chitacan** [comment]
auto merge by @chitacan :lipstick:

**Comment by chitacan** [comment]
Hi, chitacan !! what a contribute :lipstick:

**Comment by chitacan** [comment]
Hi, chitacan !! what a contribute :lipstick:

**Comment by chitacan** [comment]
Hi, @chitacan !! what a contribute :lipstick:

**Comment by chitacan** [comment]
Hi, @chitacan !! what a contribute :lipstick:

**Comment by chitacan** [comment]
Hi, @chitacan !! what a contribute :lipstick:

**Comment by chitacan** [comment]
Hi, @chitacan !! what a contribute :lipstick:

**Comment by chitacan** [comment]
Hi, @importre !! what a contribute :lipstick:

**Comment by chitacan** [comment]
Hi, importre. Thanks to contribute redribbot.

**Comment by chitacan** [comment]
@importre!! what a contribute :lipstick:

**Comment by chitacan** [comment]
@importre!! what a contribute :lipstick:

**Comment by chitacan** [comment]
Hi, importre. Thanks to contribute redribbot.

**Comment by chitacan** [comment]
importre!! what a contribute :lipstick:

**Comment by chitacan** [comment]
Hi, importre. Thanks to contribute redribbot.

**Comment by chitacan** [comment]
Hi, chitacan. Thanks to contribute redribbot.

**Comment by chitacan** [comment]
chitacan!! what a contribute :lipstick:

**Comment by chitacan** [comment]
chitacan!! what a contribute :lipstick:

**Comment by chitacan** [comment]
Hi, chitacan. Thanks to contribute redribbot.

**Comment by chitacan** [comment]
Hi, kkkkkkksk. Thanks to contribute redribbot.

**Comment by chitacan** [comment]
kkkkkkksk!! what a contribute :lipstick:

**Comment by coma333ryu** [comment]
what are you doing now?

**Comment by chitacan** [comment]
kkkkkkksk!! what a contribute :lipstick:

**Comment by chitacan** [comment]
Hi, kkkkkkksk. Thanks to contribute redribbot.

**Comment by chitacan** [comment]
chitacan!! what a contribute :lipstick:

**Comment by chitacan** [comment]
chitacan!! what a contribute :lipstick:

**Comment by chitacan** [comment]
chitacan!! what a contribute :lipstick:

**Comment by chitacan** [comment]
chitacan!! what a contribute :lipstick:

**Comment by chitacan** [comment]
chitacan!! what a contribute :lipstick:

**Pull request merged**
